In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))
def sigmoid_prime(x):
    return (1- sigmoid(x)) * sigmoid(x)

w2=np.array([[-0.2, -0.4 ],
[ 0.4, -0.4 ],
[ 0.1, 0.1 ]])
b2=np.array([[-0.5 ],
[ 0.2 ],
[ 0.1 ]])
w3=np.array([ 0.1, 0.1, 0.1 ])
b3=np.array([-0.1 ])


## feedforward network
X = np.array([[-1],[2]])
y = 2
z2 = w2 @ X + b2
a2 = sigmoid(z2)
z3 = w3@a2 + b3
a3 = sigmoid(z3)
print("z2 =");print(z2);print("a2 =");print(a2); print("z3 =");print(z3); print("a3 =");print(a3)

cost=0.5*sum((a3-y)**2)
dcost=(a3-y)
print("Cost :"); print(cost); print("a3 - y"); print(dcost)


epsilon=0.002; i=0;j=1
print('perturb one weight element, w2('+repr(i)+','+repr(j)+') and compare to gradient:')
w2p=np.copy(w2); w2p[i,j]=w2[i,j]+epsilon
y2=sigmoid(w3 @ sigmoid(w2p @X + b2) + b3)
cost2=0.5*sum((y2-y)**2)
print('finite difference grad estimate: (cost2-cost)/epsilon='+repr((cost2-cost)/epsilon))


## Backpropogation

delta3 = dcost*sigmoid_prime(z3)
print("delta3 = ");print(delta3)
nabla_b3 = delta3
print("nable_b3 = "); print(nabla_b3)
nabla_w3 = delta3@a2.T
print("nabla_w3 = "); print(nabla_w3)

delta2 = (w3.T*delta3) *sigmoid_prime(z2).T
print("delta2 =");print(delta2)
nabla_b2 = delta2.T
print("nabla_b2 = "); print(nabla_b2)
nabla_w2 = delta2.T @X.T
print("nabla_w2 = ");print(nabla_w2); 
print("If we see the second element of the first row of nabla_w2, we can see the gradient for element w2_12 is ");
print('-0.01403653 same as the gradient we calculated using the perturbation approach which is -0.01405048.');
print("Therefore we yield same results from backpropagation but in a faster and efficient way.")
## Steepest Descent iteration

eta=1
w2=w2-eta*nabla_w2; b2=b2-eta*nabla_b2
w3=w3-eta*nabla_w3; b3=b3-eta*nabla_b3

print("Weights and Biases after Steepest Descent iteration: ")
print("w2 = ");print(w2); print("b2 = "); print(b2); print("w3 = "); print(w3); print("b3 = "); print(b3)
y_p = sigmoid(w3 @ sigmoid(w2 @X + b2) + b3)
print("y predicted = "); print(y_p)
print("New Cost = "); print(0.5* sum(y_p - y)**2)



z2 =
[[-1.1]
 [-1. ]
 [ 0.2]]
a2 =
[[0.24973989]
 [0.26894142]
 [0.549834  ]]
z3 =
[0.00685153]
a3 =
[0.50171288]
Cost :
1.1224321527825747
a3 - y
[-1.49828712]
perturb one weight element, w2(0,1) and compare to gradient:
finite difference grad estimate: (cost2-cost)/epsilon=-0.014050485870331642
delta3 = 
[-0.37456739]
nable_b3 = 
[-0.37456739]
nabla_w3 = 
[-0.09354442 -0.10073668 -0.20594988]
delta2 =
[[-0.00701826 -0.00736444 -0.00927116]]
nabla_b2 = 
[[-0.00701826]
 [-0.00736444]
 [-0.00927116]]
nabla_w2 = 
[[ 0.00701826 -0.01403653]
 [ 0.00736444 -0.01472888]
 [ 0.00927116 -0.01854233]]
If we see the second element of the first row of nabla_w2, we can see the gradient for element w2_12 is 
-0.01403653 same as the gradient we calculated using the perturbation approach which is -0.01405048.
Therefore we yield same results from backpropagation but in a faster and efficient way.
Weights and Biases after Steepest Descent iteration: 
w2 = 
[[-0.20701826 -0.38596347]
 [ 0.39263556 -0.385

In [ ]:
X_1=np.array([[3,6,1,0,5,5,4,4,3,4,6,3,2,5,4,8,6,8, 9,8,3,6, 1,4,7,2,9,1,4,2,9,1,5],
[9,1,5,7,5,5,2,2,2,0,2,4,1,2,9,8,8,10,1,3,4,6,10,7,2,7,4,9,4,6,8,9,4]])
y_1=np.array([2,3,1,1,3,3,3,3,1,3,3,1,1,3,2,2,2, 2,3,3,1,2, 1,2,3,1,2,1,1,1,2,1,3])-1




In [ ]:
import tensorflow as tf
import tensorflow 

from tensorflow import keras
from keras.layers import Dense


In [2]:
conda install tensorflow

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for anaconda nbconvert spyder ipykernel jupyter_client jupy| 
Note: you may need to restart the kernel to use updated packages.
