In [1]:
import numpy as np

In [11]:
A = np.array([[4,1,3], [-4,-2,-5],[3,-1,-4], [0,4,-1]])
b = np.array([[0], [5], [-1], [-2]])
print("The Matrix A = "); print(A)
print("The b vector = "); print(b)
x = np.linalg.inv(np.matmul(A.T, A)) @ A.T @b
print('The Least squares solution (A.T A)^-1 A.T b = x = '); print(x)
r= A@x - b
print("The residual vector r = "); print(r); print("norm of r = ") ;print(np.linalg.norm(r,2))
print("norm of b = ") ;print(np.linalg.norm(b,2))
x1,residuals,rank,sigma=np.linalg.lstsq(A,b,rcond=None)
print("Python solution using np.linalg.lstsq, x = "); print(x1); print("r = "); print(residuals)

The Matrix A = 
[[ 4  1  3]
 [-4 -2 -5]
 [ 3 -1 -4]
 [ 0  4 -1]]
The b vector = 
[[ 0]
 [ 5]
 [-1]
 [-2]]
The Least squares solution (A.T A)^-1 A.T b = x = 
[[-0.40227759]
 [-0.56657582]
 [-0.07037181]]
The residual vector r = 
[[-2.38680164]
 [-1.90587892]
 [ 0.64123029]
 [-0.19593148]]
norm of r = 
3.1271012013207278
norm of b = 
5.477225575051662
Python solution using np.linalg.lstsq, x = 
[[-0.40227759]
 [-0.56657582]
 [-0.07037181]]
r = 
[9.77876192]


In [14]:
import scipy.linalg

In [32]:
a = np.array([[-0.4, 0.2, -0.7], [0.8, -0.7, -0.1]])
bb = np.array([[-1], [0.5]])
U, S, V = scipy.linalg.svd(a)
print(U);print(S); print(V.T)
x2=scipy.linalg.pinv(a)@bb
print("Solution using x2=scipy.linalg.pinv(A)@b = "); print(x2)
x3, residuals, rank, sigma = np.linalg.lstsq(a, bb,rcond = None)
print("The least squares solution to the under determined system is x = "); print(x3)

[[ 0.50013875  0.86594528]
 [-0.86594528  0.50013875]]
[1.1684391 0.6817258]
[[-0.76410634  0.07881892 -0.64025704]
 [ 0.60438704 -0.25950033 -0.75324358]
 [-0.22551676 -0.96252125  0.15064872]]
Solution using x2=scipy.linalg.pinv(A)@b = 
[[ 0.53900709]
 [-0.24822695]
 [ 1.04964539]]
The least squares solution to the under determined system is x = 
[[ 0.53900709]
 [-0.24822695]
 [ 1.04964539]]
